### ISSUE TITLE
Implement VC handling in stage2 and COCONUT kernel

### ISSUE THREAD

**Issue by joergroedel** [coconut-svsm/svsm#14]
Move away from directly making GHCB calls and implement a proper #VC exception handler to handle NAE events.

This is required for CPL-3 support, as some instructions that cause NAEs are allowed in unprivileged code (e.g. CPUID). But the console printing support also benefits from this, as its driver infrastructure can be removed so that it uses IN/OUT instructions directly.

Further, by handling #VC exceptions in stage2 already we can get console support very early in the COCONUT kernel, which makes debugging of the early boot stages much easier.

There is no reason yet to handle MMIO related NAE events, but IOIO is needed, best including INS/OUTS instructions (but these are not needed in the first step).

**Comment by 00xc** [comment]
Can we close this, since #55 is merged?

**Comment by p4zuu** [comment]
> Can we close this, since #55 is merged?

I guess so. There are still improvement to do, like implementing all NAE events handlers, and making #VC handler IST, on which I plan to work soon, but I let @joergroedel decide on the closing

**Comment by stefano-garzarella** [comment]
@joergroedel I'm closing this, feel free to re-open it if you think more work is needed.
