### ISSUE TITLE
I'm not sure exactly how to use SVSM.

### ISSUE THREAD

**Issue by ksy980324** [coconut-svsm/svsm#289]
I installed SVSM normally.
I also verified that the guest VM is working on VMPL1.

My reason for using SVSM is that I want to take advantage of VMPL features.
I'm not sure exactly how this framework works as there is a lot I don't know.

I would like to increase the VMPL permissions of certain software running on the VM.
Can you explain how this works?

**Comment by joergroedel** [comment]
Please refer to the [INSTALL.md](https://coconut-svsm.github.io/svsm/installation/INSTALL/) document on how to setup and run COCONUT-SVSM.

**Comment by stefano-garzarella** [comment]
@ksy980324 can we close this issue?
