### ISSUE TITLE
Compile errors while building coconut-svsm

### ISSUE THREAD

**Issue by ramagali24** [coconut-svsm/svsm#374]
error[E0405]: cannot find trait `Copy` in this scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typenum-1.17.0/src/array.rs:303:10
    |
303 |     Rhs: Copy,
    |          ^^^^ not found in this scope

error[E0433]: failed to resolve: use of undeclared type `P3`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typenum-1.17.0/src/type_operators.rs:245:14
    |
245 |     let p3 = P3::new();
    |              ^^ use of undeclared type `P3`

error[E0433]: failed to resolve: use of undeclared type `U0`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typenum-1.17.0/src/type_operators.rs:247:14
    |
247 |     let u0 = U0::new();
    |              ^^ use of undeclared type `U0`

error[E0433]: failed to resolve: use of undeclared type `U3`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typenum-1.17.0/src/type_operators.rs:248:14
    |
248 |     let u3 = U3::new();
    |              ^^ use of undeclared type `U3`

error[E0433]: failed to resolve: use of undeclared type `N3`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typenum-1.17.0/src/type_operators.rs:249:14
    |
249 |     let n3 = N3::new();
    |              ^^ use of undeclared type `N3`

Some errors have detailed explanations: E0405, E0412, E0432, E0433, E0463.
error: could not compile `typenum` (lib) due to 150 previous errors
make: *** [Makefile:114: bin/stage2.bin] Error 101

**Comment by 00xc** [comment]
Which Rust toolchain version (`rustc --version`) are you using?

**Comment by ramagali24** [comment]
rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)

**Comment by ramagali24** [comment]
I am able to clear previous errors by updating tools again and right now i see below errors. Any suggestions.
rustc-LLVM ERROR: Do not know how to split the result of this operator!

error: could not compile `polyval` (lib)
warning: build failed, waiting for other jobs to finish...
rustc-LLVM ERROR: Do not know how to split the result of this operator!

error: could not compile `aes` (lib)
make: *** [Makefile:118: bin/svsm-kernel.elf] Error 101

**Comment by 00xc** [comment]
> I am able to clear previous errors by updating tools again and right now i see below errors. Any suggestions. rustc-LLVM ERROR: Do not know how to split the result of this operator!
> 
> error: could not compile `polyval` (lib) warning: build failed, waiting for other jobs to finish... rustc-LLVM ERROR: Do not know how to split the result of this operator!
> 
> error: could not compile `aes` (lib) make: *** [Makefile:118: bin/svsm-kernel.elf] Error 101

Those errors should be removed by these two lines:

https://github.com/coconut-svsm/svsm/blob/1d7eb9b1b7af798ca1631b005244cefdc6b97ff2/.cargo/config.toml#L6-L7

So I'm not sure what's going on here.

**Comment by ramagali24** [comment]
I could resolve this issue after sync i went to "libmstpm" and do clean and compile.
And then comeback to home svsm folder and did proceed with compilation.

I will update my findings in installation document for approval.
