### ISSUE TITLE
Migrate to official TPM ref code

### ISSUE THREAD

**Issue by jyao1** [coconut-svsm/svsm#440]
Current code is using https://github.com/coconut-svsm/svsm/tree/main/libmstpm/deps.

Feedback from James Bottomley <James.Bottomley@HansenPartnership.com>

==============

Just a note for the vTPM reference implementation which, I think,
applies to both you and the current SVSM-vTPM: the reference TPM
implementation has moved to

https://github.com/TrustedComputingGroup/TPM

And the one you list (https://github.com/microsoft/ms-tpm-20-ref) is
now a stale copy that isn't being kept up to date.

==============

**Comment by stefano-garzarella** [comment]
As we discussed yesterday in the community call, I'll look into this issue in the next days in order to move our TPM to https://github.com/TrustedComputingGroup/TPM
