### ISSUE TITLE
State of SVSM with Linux 6.11?

### ISSUE THREAD

**Issue by CookieComputing** [coconut-svsm/svsm#449]
Hi folks,

Bit of a newcomer to SVSM, but I was wondering what the state of coconut-svsm was with the announcement of some SVSM patchs being checked in [Linux 6.11](https://www.phoronix.com/news/AMD-SEV-SNP-SVSM-Linux-6.11). From what I can tell in [this merge](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=408323581b722c9bd504dd296920f392049a7f52), some core components for SNP + SVSM were checked into the Linux 6.11 rc, but I'm unsure if there's additional work beyond this given that the [installation instructions](https://github.com/coconut-svsm/svsm/blob/main/Documentation/docs/installation/INSTALL.md) still suggest that things haven't been upstreamed yet. Is it simply because these docs haven't been updated yet?

For instance, it seems like the [svsm host section](https://github.com/coconut-svsm/svsm/blob/main/Documentation/docs/installation/INSTALL.md#preparing-the-host) indicates that the current host kernel is still based on the 6.5 kernel, but with the 6.11 merge, I'm not sure if this is still correct. It also seems like the latest changes to the linux fork were [five months ago](https://github.com/coconut-svsm/linux/tree/svsm), whereas the changes for SVSM in 6.11 landed last month. Is there anywhere I can search to find the most up-to-date information? I couldn't find a similar issue which talks about the most recent patches to the upstream kernel.

**Comment by Freax13** [comment]
Hi!

As you already noticed, there are two sides to this: The kernel needs changes to act as an SVSM guest and it needs changes to act as an SVSM host. The announcement you referred to is about some core SNP host changes and SVSM guest patches being merged. As a result Linux 6.11 doesn't support acting as a SVSM host yet, but it might support acting as a guest (I haven't actually tried it, but it *should* work). Our fork is needed to run a host.

> For instance, it seems like the [svsm host section](https://github.com/coconut-svsm/svsm/blob/main/Documentation/docs/installation/INSTALL.md#preparing-the-host) indicates that the current host kernel is still based on the 6.5 kernel, but with the 6.11 merge, I'm not sure if this is still correct.

Two things: 1. That version number in the docs is slightly out of date, the kernel is actually based on Linux 6.8. 2. As I explained above, upstream Linux 6.11 is not sufficient to run a host, so our fork still has to be used.

> It also seems like the latest changes to the linux fork were [five months ago](https://github.com/coconut-svsm/linux/tree/svsm), whereas the changes for SVSM in 6.11 landed last month.

There are efforts to update our fork for the host kernel to a newer Linux version: https://github.com/coconut-svsm/linux/pull/6.

> Is there anywhere I can search to find the most up-to-date information? I couldn't find a similar issue which talks about the most recent patches to the upstream kernel.

AFAICT, the section about the host part is mostly up to date (except for the version number). I'm not too sure about the guest part, Linux 6.11 might work or it might not. If you're just trying to get something up and running just following the docs is probably easiest, they might not use the newest possible kernels, but running the latest SVSM with it should work.

**Comment by CookieComputing** [comment]
Hi! Thanks for letting me know. I'm currently trying to launch with SVSM enabled using Roy's latest patches for the 6.11 kernel + QEMU. We can probably close this to avoid polluting the open issues backlog!
