### ISSUE TITLE
How to pass path of shimx64.efi during boot of coconut-svsm

### ISSUE THREAD

**Issue by EdgeSync** [coconut-svsm/svsm#457]
Hey, 

I am having an issue where when I start up the coconut-svsm, it is unable to find the shimx64.efi in order to boot the vm. 
This means every time I start the VM, I need to go into the BIOS, and manually find the .efi file.

From what I understand, the problem is due to the OVMF_VARS file being read only, and so is not able to store the .efi file location. 

I was digging around on the QEMU docs (https://www.qemu.org/docs/master/specs/fw_cfg.html) and see they have an option fw_cfg. I tried passing in the location of the shim `-fw_cfg name=opt/bootscript,string="fs0:\EFI\ubuntu\shimx64.efi"` but still it doesn't boot. I think I am very close, but maybe am not using the command correctly. 

Any ideas / suggestions to get it to point at the .efi every time, instead of manually finding it in the bios/boot menu?

**Comment by osteffenrh** [comment]
Yes, the EFI variables are not preserved. That means one cannot customize the boot settings.

The default approach is to use the EFI removable media/fallback bootloader path `$ESP/EFI/BOOT/BOOTX64.EFI`. If you copy your shim to there it could work.

I have not tried the `fw_cfg` approach.

**Comment by chris-s-hpe** [comment]
Just wanted to come back and say thanks @osteffenrh You were able to help point me in the right direction. 

So copying the shimx64.efi to the BOOT directory didn't work to boot the VM. Interestingly BOOTX64.EFI and shimx64.efi were the same file (same hash)

```
root@amd-1:/mnt/vm/EFI# md5sum */*
07e25dcaf57c776875f78fa36827c58e  BOOT/BOOTX64.EFI
07e25dcaf57c776875f78fa36827c58e  ubuntu/shimx64.efi
```

But if i chose BOOTX64.EFI the VM wouldn't boot, and if i chose shimx64.efi, it would. Funky behavior that I don't really understand 😄 

Anyways what worked for me:

copy /EFI/ubuntu/shimx64.efi to /EFI/BOOT/
copy /EFI/ubuntu/grubx64.efi to /EFI/BOOT/BOOTX64.EFI (overwrite BOOTX64.EFI) 

And then my VM booted as normal each time it powered on. No more need to drop into UEFI shell and find the shim manually.
