### ISSUE TITLE
stage2 trusts VMM provided addresses

### ISSUE THREAD

**Issue by Freax13** [coconut-svsm/svsm#5]
Why can stage2 trust the VMM's addresses provided here? 

https://github.com/coconut-svsm/svsm/blob/b8042679f07d24dc0a6df53cf73b278eb545a8fd/src/fw_cfg.rs#L123-L132

AFAICT the data read here is not attested or verified and the VMM can respond with anything it wants.

**Comment by Freax13** [comment]
> The SVSM can't trust this information, but at the same time it has no choice other than to use it. It is at the same level as the hypervisor-provided memory layout information or available APIC-IDs. Both come from the hypervisor and there no more secure source for it.

But for the addresses here specifically, isn't that a security problem, though? AFAICT, an evil hypervisor can swap the addresses to something else that will then be executed.

Even if there is no way for the guest to derive to addresses itself, it should still be possible to verify that the hypervisor provided the correct information, e.g, by hashing the kernel and checking to result.

**Comment by joergroedel** [comment]
> But for the addresses here specifically, isn't that a security problem, though? AFAICT, an evil hypervisor can swap the addresses to something else that will then be executed.

No, not really. The address in that file are not used as jump targets. It is exclusively used in stage2 to find a decent memory location to relocate the SVSM kernel to. For that it is called only once and everything else is in the hands of the SVSM code.

> Even if there is no way for the guest to derive to addresses itself, it should still be possible to verify that the hypervisor provided the correct information, e.g, by hashing the kernel and checking to result.

Not sure what you mean, the file read above is not used to load the SVSM kernel into memory. It is only used to determine the address range that is reserved for the SVSM within guest memory. There is also a check for the file-size, which must be 16 bytes (two 64-bit values).

**Comment by Freax13** [comment]
Oh, okay, I think the misunderstanding here is that I thought the addresses read from the file specify where the kernel is copied **from**, but they actually specify where the kernel is copied **to**.

But still, couldn't this be used to corrupt the loader's memory by specifying the physical memory backing the loader as the destination for the SVSM?

**Comment by joergroedel** [comment]
Yeah, a check that the region does not overlap with stage2 memory might be beneficial. On the other hand, this code might be removed anyway when OVMF can correctly handle the SVSM location announced in the secrets page.
We tried to change OVMF to handle that but ran into issues with later boot stages. But situation in general improved with the SNP-v8 patch-set, so we might give it another try.

**Comment by joergroedel** [comment]
Okay, to get this to a conclusion. I am fine with adding a check to make sure the reported SVSM memory region does not cover the first 640k of memory. The code is there and currently in use, so we better do the check.

**Comment by joergroedel** [comment]
> If I'm interpreting this correctly, this allows the host to grant VMPL1 access to arbitrary memory locations thus breaking the isolation between VMPL0 and VMPL1.

Yes, that is problematic as we have to trust QEMU here. Some sanity checking would definitly be desired.

**Comment by Freax13** [comment]
How would we check that? Is it enough to check if the regions overlap with the kernel region? Does the kernel region contain all VMPL0 exclusive memory (i.e. are all the heaps etc. in this region)? Is there another way to check?

**Comment by joergroedel** [comment]
Best is to check that the regions are between 3GiB and 4GiB in the physical address space and that one region ends at exactly 4GiB. Also that the regions do no overlap wrt. each other, that they don't overlap with SVSM kernel memory or with Stage2 memory (0-640KiB)

**Comment by Freax13** [comment]
>  Stage2 memory (0-640KiB)

The loader is already invalidated at this point. Do we still need to check and why?

**Comment by Freax13** [comment]
We also need to ensure that the physical addresses don't have any bits out of range set.
