### ISSUE TITLE
Implement support for requesting a VMPL0 attestation report

### ISSUE THREAD

**Issue by cclaudio** [coconut-svsm/svsm#67]
## Relevant documents

1. [SEV-SNP Firmware ABI spec](https://www.amd.com/system/files/TechDocs/56860.pdf):
    - Chapter 7: Guest messages
    - Section 7.3: Attestation

2. [GHCB spec](https://www.amd.com/system/files/TechDocs/56421-guest-hypervisor-communication-block-standardization.pdf):
    - Chapter 4 - GHCB protocol
    - Section 4.1.7 - SNP Guest Request
    - Section 4.1.8 - SNP Extended Guest Request

## Some consumers for this feature

- [Attestation Protocol](https://lore.kernel.org/linux-coco/a2f31400-9e1c-c12a-ad7f-ea0265a12068@amd.com/2-Draft-SVSM-v0.62.pdf)
- Virtual TPM can use it to bind the vTPM to the guest

**Comment by cclaudio** [comment]
This feature requires crypto support. According to the spec, a VPML0 attestation report request has to be encrypted with the VMPCK0 key and using AES_256_GCM.

I am implementing this feature leveraging [RustCrypto](https://crates.io/crates/rust-crypto), which is a pure Rust implementation for various crypto algorithms (there is no C blobs). With that, I think it's OK if we encrypt the attestation report message in ring0.

If later we find out that there is a more suitable crypto option, we should be able to replace RustCrypto without much rework. For the attestation report purpose, we need to do only a few RustCrypto calls and the RustCrypto dependencies are self-contained in Rust packages.

**Comment by mbs0221** [comment]
It would be better if we can build purely in Rust without third-party bindgens.

**Comment by osteffenrh** [comment]
From the RustCryto's website:

> Rust-Crypto has not been thoroughly audited for correctness, so any use where security is important is not recommended at this time.

That is probably ok for now, but we'll have to come back to this before we can ship for production (at some point in the future).
