### ISSUE TITLE
Where is the manual for setting GHCBExitCode::RUN_VMPL=0x80000018

### ISSUE THREAD

**Issue by LouXiaoxuan** [coconut-svsm/svsm#88]
The latest SEV GHCB standarization doesn't mention how to set the context for RUN_VMPL (0x80000018) and the inner mechanism of this GHCBExit is not clear. So, where can I find more details about this GHCBExit event?

**Comment by tlendacky** [comment]
I am working on getting the finalized version of the GHCB specification with the SVSM support published to our web site. In the mean time, a draft version of the spec can be found here: https://lore.kernel.org/linux-coco/a4b8da44-89d3-c34b-f1cf-8d247835b4f7@amd.com/T/#m21129e7acf73318687113f424fcef0ee63257a81

**Comment by LouXiaoxuan** [comment]
Thanks for the prompt response! I'll close this issue.
